### ISSUE TITLE
Mod1_Lab2_Ex2_Task2_Step7 - Program.cs does not contain code to update

### ISSUE THREAD

**Issue by MOC-Labs-Review** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#106]
# Module: 1 - Implement Microsoft identity
##### Step: 7

Description of issue
The instructions in Steps 6 to 8 state to update code in file Program.cs.  The file does not contain the specific code referenced to update and therefore no updates can be made. Skipping these steps causes an error in later steps (see screenshot below).  This is also a problem in subsequent labs and tasks.  As a note, in reviewing the previous issues I noticed the instructions in the screenshots in issue #54 were using file Startup.cs.

Below is a copy of the code in Program.cs showing there is no mention of: builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme).AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"));

Program.cs
1.	using System;
2.	using System.Collections.Generic;
3.	using System.Linq;
4.	using System.Threading.Tasks;
5.	using Microsoft.AspNetCore.Hosting;
6.	using Microsoft.Extensions.Configuration;
7.	using Microsoft.Extensions.Hosting;
8.	using Microsoft.Extensions.Logging;
9.	
10.	namespace IdentityWeb
11.	{
12.	    public class Program
13.	    {
14.	        public static void Main(string[] args)
15.	        {
16.	            CreateHostBuilder(args).Build().Run();
17.	        }
18.	
19.	        public static IHostBuilder CreateHostBuilder(string[] args) =>
20.	            Host.CreateDefaultBuilder(args)
21.	                .ConfigureWebHostDefaults(webBuilder =>
22.	                {
23.	                    webBuilder.UseStartup<Startup>();
24.	                });
25.	    }
26.	}
27.	

After skipping the steps, this is the error that occurred:
![image](https://user-images.githubusercontent.com/91673275/172628589-10af968c-334e-4e3e-be01-8b0a1038cd97.png)

**Comment by b-deen** [comment]
This lab has been removed.  Closing this issue.
