### ISSUE TITLE
Git clone Filename too long

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#107]
# Module: 00
#### Step: 00

Description of issue
Please give the instructions a shorter file name....
![image](https://user-images.githubusercontent.com/10166617/173572037-818b462d-6547-44bb-96b0-000157673e0a.png)

Repro steps:

1. Cmd
1. cd c:\
1. mkdir git
2. git clone this repository

**Comment by b-deen** [comment]
Hello, thank you for sharing this issue.  We will look into whether or not we can rename the repo, but in the meantime here are 2 workarounds for anyone having issue with the filename length:
1. Run **git clone <repo> <newfoldername>** to rename the folder you wish to clone into.
2. Create a folder with a shorter filename, navigate into it, and then run **git clone <repo> .** to clone the repo contents into the folder you created.

I believe either of these options should prevent any issues with the current repo name.
