### ISSUE TITLE
Broken link for Microsoft 365 tenant

### ISSUE THREAD

**Issue by richard-b2** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#108]
# Module: 05
#### Step: 00

Description of issue:

The link https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/blob/master/microsoftteams/platform/get-started/get-started-tenant gives a 404 error. 

It appears in a number of labs where "Developing Microsoft Teams apps requires a Microsoft 365 tenant, Microsoft Teams configured for development, and the necessary tools installed on your workstation."

**Comment by b-deen** [comment]
Thank you for submitting the issue.  This has been resolved.
