### ISSUE TITLE
Module 04 Bot related labs have issues and missing many updates in the lab instructions

### ISSUE THREAD

**Issue by ZuberAgwan** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#112]
# Module: 04
#### Step: All module 04 Steps

Description of issue

All the lab streps in the Module 04 needs serious attention and also has out dated code in the steps

Additionally, Lab instructions needs to be in proper order.

there are many repeated steps that can be avoided in all the and can be clubbed in one lab per module with all examples in order

Also, sample code should be included in the lab files

Please update the lab guides and the outdated code snippets in this course

**Comment by b-deen** [comment]
Thank you for your feedback.  The labs are currently being reviewed and updated.  The need for solution files and condensed labs is understood and being evaluated for future iterations of the content.
