### ISSUE TITLE
LP 01 Mod 01: server.js web app fails to reflect signed-in status with BrowserAuthError: hash_empty_error

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#116]
- Learning Path 01 - Implement Microsoft Identity
- Module 01 - Getting started with Microsoft Identity
- Exercise 1: Different types of tokens used in Microsoft identity
- Task 5: Test the web application
- Step 5

When testing the `server.js` local web app at the above lab step, expected results are not displayed as shown in the [screenshot of the default web page for an authenticated user](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/blob/b93a2b43dc09cec77214b17f60b23bd9ae3fc2dc/Instructions/Labs/Linked_Image_Files/01-01-03-test-03.png) included in the lab instructions.

After completing all required steps in the Microsoft login popup launched when the "Sign In" button is first clicked within the local web app, with all messages within the popup indicating a successful authentication, no change is reflected in the local web app page. The sign-in button does not change to display the text "Sign Out", and no JSON output is displayed. Further clicks of the sign-in button result in a login popup that instantly closes after it starts to appear.
 
The browser console displays a "BrowserAuthError: hash_empty_error" message after the login popup (which appeared to successfully authenticate) completes (see below screenshot).

![js-error](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/134323425/8b9a78bc-527b-4d58-bce3-602bb3935844)

Additional screenshots:

[Unchanged page contents with JS error](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/134323425/920b8078-ed0d-4402-84a6-4ca5a6d26d71)

[Login popup](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/134323425/d615ea04-a6c1-426f-81de-d765c968fc8c)

**Comment by b-deen** [comment]
This issue will be closed as these exercises have been removed from the course.  Please see the course change log for more information about the changes.
