### ISSUE TITLE
Learning Path 02 Exercise 1 dotnet build of application fails

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#117]
# Exercise: 01
#### Step: 18

Description of issue
First dotnet build of Exercise 1, Task 1 in Learning Path 02 fails with several authentication provider not found errors.

Repro steps:

1. Attempt to use command prompt to run dotnet build to deploy the console app. Command fails that the authentication provider cannot be found.

![image](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/94069201/6ea5d46b-9f41-42df-be90-e8d6c48da721)

**Comment by b-deen** [comment]
Hi, thanks for logging this.  Can you clarify which exercise you're referencing? You noted Learning Path 2 (Graph).  This learning contains 6 module folders and each of those folders contains numbered exercises.  You noted Exercise 1, but can you provide the name/number of the module, please (for all issues logged)?  

So, we'll need LP#, Module #, and Exercise # for all issues.   

Many of the exercises contain similar steps for running the application at the end of the exercise, so I want to make sure I'm testing the correct exercise. Thank you!

**Comment by b-deen** [comment]
No problem.  Can you provide which module you are in, please?  The exercise #s start over for each module within the learning path.

**Comment by brookbeckertesting** [comment]
Module 1, Optimize data usage

**Comment by b-deen** [comment]
Ok thanks!

**Comment by PadmaPK08** [comment]
I am facing the same issue, how can this be resolved?

**Comment by b-deen** [comment]
This issue will be closed as these exercises have been removed from the course.  Please see the course change log for more information about the changes.
