### ISSUE TITLE
LP 01 Mod 04: ProductCatalog package, build errors

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#118]
- Learning Path 01 - Implement Microsoft Identity
- Module 04 - Secure custom APIs with Microsoft Identity
- Exercise 1: Create and secure a web API with Microsoft identity
- Task 2: Create a .NET Core web API application

There is likely some redundancy in the below sequence of error reports, but for reference purposes, all errors observed while continuing through the lab steps are provided.

#### Step 2

The command `dotnet new webapi -o ProductCatalog -au singleorg` results in the package error messages below within the `dotnet restore` section of command output.

```
C:\Users\Admin\ms600-ex1b\ProductCatalog\ProductCatalog.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Authentication.JwtBearer. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
C:\Users\Admin\ms600-ex1b\ProductCatalog\ProductCatalog.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Authentication.OpenIdConnect. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
C:\Users\Admin\ms600-ex1b\ProductCatalog\ProductCatalog.csproj : error NU1101: Unable to find package Microsoft.Identity.Web. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
C:\Users\Admin\ms600-ex1b\ProductCatalog\ProductCatalog.csproj : error NU1101: Unable to find package Swashbuckle.AspNetCore. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
```

[Step 2 screenshot](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/134323425/0aa29695-934b-4113-b764-519f6abc1209)

#### Step 3

The command `dotnet add package Microsoft.Identity.Web` fails with the package error below.

```
error: There are no versions available for the package 'Microsoft.Identity.Web'.
```

[Step 3 screenshot](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/134323425/15eddb0b-ab3b-491d-9600-396338111ba7)

#### Step 4

After opening the project in VSCode and installing the recommended C# extension, a popup message refers to issues loading, and OmniSharp package errors appear in the output pane.

```
[fail]: OmniSharp.MSBuild.ProjectLoader
        Unable to find package Microsoft.AspNetCore.Authentication.JwtBearer. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[fail]: OmniSharp.MSBuild.ProjectLoader
        Unable to find package Microsoft.AspNetCore.Authentication.OpenIdConnect. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[fail]: OmniSharp.MSBuild.ProjectLoader
        Unable to find package Microsoft.Identity.Web. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[fail]: OmniSharp.MSBuild.ProjectLoader
        Unable to find package Swashbuckle.AspNetCore. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
```

[Step 4 screenshot](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/134323425/500ce5a0-e389-41ee-8896-09d5b5dc104e)

#### Step 6

Note: additional steps not listed in instructions are required to configure the specific `.NET Core Launch (web)` template within launch.json after creating it via the Run & Debug page.

[launch.json used in this lab session](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/files/11772517/launch.json.txt)

#### Step 14

Command `dotnet add package Bogus` fails in same manner as the command in step 3.

```
error: There are no versions available for the package 'Bogus'.
```

### Running the ProductCatalog project

The `ProductCatalog` project configured in Exercise 1 is built for the first time at instruction step :

- Exercise 2: Call secured APIs from web applications
- Task 2: Create a single organization ASP.NET web application
- step 23

> On the Visual Studio Code menu bar, select Run > Run Without Debugging to start the web API.

As the package errors above were previously encountered, it is not surprising that the project fails to run. In general, previous package errors are "ignorable", as directly subsequent lab steps do not strictly rely on successful `dotnet restore` routines, etc. A hard failure of the `ProductCatalog` project will first be observed when attempting to run it at the above-referenced step. 

The observed behavior is below.

After selecting "Run Without Debugging", the below popup appears. Configure task was selected, then "create tasks.json file from template". The ".NET Core" option was selected and a `tasks.json` file created.

![Screenshot 2023-06-16 082810](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/134323425/57e32969-7a15-4b33-ba98-acf1dcd8df1d)

[tasks.json step 1](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/134323425/53c8abd6-644e-4f62-8fd4-d3e647f99cff)

[tasks.json step 2](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/134323425/2518f188-1278-4a96-b46e-47ee1ec9d8cb)

[tasks.json content](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/134323425/cd6f19c9-92b8-4342-932d-55eee534a5aa)

After re-running via Run Without Debugging, the below `dotnet build [...]` terminal output and error popup are shown within VSCode. These error messages echo the `error NU1101` messages observed at Ex 1 Task 2 step 2.

![Screenshot 2023-06-16 083849](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/134323425/fb566d47-e112-4580-95c2-2d10636f5c66)

**Comment by dipali1709** [comment]
I faced the same issue so I changed the Dotnet SDK version from V6-400 to V6-202  and it worked for me. I suggest to install the dotnet version v6-202.

**Comment by mafuerst** [comment]
I am also having the same issue

**Comment by dipali1709** [comment]
> I am also having the same issue

Try changing the Dotnet SDK version from V6-400 to V6-202

**Comment by b-deen** [comment]
Thank you for submitting, and for those who validated the issue.  These exercises are being reviewed.  We'll update the instructions to reflect the appropriate tooling requirements.

**Comment by b-deen** [comment]
Closing issue as we have removed these exercises from the course.
