### ISSUE TITLE
Initial Lab Setup

### ISSUE THREAD

**Issue by ank-git** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#12]
What is the initial lab setup to perform the labs? Seems like a student has to create a Virtual Machine on Azure using an Azure Pass. However if that is the case then please share the instructions to create a virtual machine on Azure. Also please share the list of applications to install inside the virtual machine. If there is any ARM template to deploy, then share the same as the one which is given inside demo folder, doesn't creates a virtual machine on Azure. 

Please help.

**Comment by b-deen** [comment]
Hello, thank you for reaching out.  The required VMs, tenant and Azure pass for the labs are supplied when the course is delivered through an automated lab hoster.  Please let me know if you need more information.

**Comment by ank-git** [comment]
I am MCT. I need to test and perform the labs. How will I get an access of the VM and tenant.

**Comment by b-deen** [comment]
Hello, as an MCT you have access to the labs for free through the MCT Readiness program for trainer prep. The details should be in your MCT benefits package and it should detail how you access the labs.  Happy to help if you have additional questions.

**Comment by j-ankur** [comment]
Hi, I have checked on XtremeLabs and the labs for this course are not hosted. Neither on LearnOnDemand. Kindly help

**Comment by j-ankur** [comment]
If you can provide me the VM template alongwith the applications required for the labs, then it will be great.

**Comment by b-deen** [comment]
Hello, the VM requirements are as follows.  I am following up with our team re: your inability to access/locate the hosted lab environment for this course.  

![image](https://user-images.githubusercontent.com/28913786/83430735-2c671900-a404-11ea-883c-981b4d3b350e.png)

**Comment by j-ankur** [comment]
Thank u for your reply. However I would appreciate if you can expedite the
process.

**Comment by b-deen** [comment]
Of course, I know this is a frustrating experience and thank you for your patience.  I reached out to the team prior to responding to you today.  We are working with the lab hosters to determine why the labs for this course are not hosted and when they will be.  I will follow up as soon as we have further guidance.

**Comment by b-deen** [comment]
Hello, we haven't yet heard from Xtreme Labs, but if you would be interested in using GoDeploy's hosting solution for a class offering, you could reach out to them for access at support@godeploy.it.  That's the only provider currently hosting the labs for this course.  We are still following up with the others.

**Comment by j-ankur** [comment]
Thank you for the information. Just to clarify if you could provide me a VM
template used for this training that would be great

**Comment by b-deen** [comment]
Hello, can you please clarify whether you are seeking access to the lab environment for your own testing or for use in an ILT?

**Comment by j-ankur** [comment]
ILT

**Comment by ank-git** [comment]
Hi !! Any luck on this ?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by b-deen** [comment]
Hello,

I was told there is not a template available for this course.  The best option would likely be to work with the lab hoster so you have the tenant and azure pass required, but I’ve also provided the information for the VM and applications used for the course.

Please let me know if you need anything else.
________________________________

**Comment by j-ankur** [comment]
Ok. But the labs are not available with lab boaters then how to perform
labs ?

**Comment by b-deen** [comment]
Currently Go Deploy is the only option for lab hosting for this course, but we are told it will be available throgh Learn on Demand Systems this month.  I'm not sure when your training will be held.  I provided Go Deploy's contact info above (support@godeploy.it).

**Comment by b-deen** [comment]
Update: Xtreme Labs is currently re-staging the hosted labs for this course.  Hosted labs for this course will be available through Xtreme Labs next week.

**Comment by j-ankur** [comment]
How to get access codes for Xtremelabs for my students?

**Comment by j-ankur** [comment]
Also when the labs will be available on Learn on Demand?

**Comment by b-deen** [comment]
Hello,

The MCT support channel found here<https://trainingsupport.microsoft.com/en-us> will be best able to assist you with these questions about lab hosting and access.  The GitHub repo should be used to share issues with/updates to the lab content for this course to help us keep the content accurate and up-to-date.  If you have any trouble accessing the support channel, let me know and I’ll loop someone in.
