### ISSUE TITLE
Learning path 04 Bot issue

### ISSUE THREAD

**Issue by mafuerst** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#120]
# Module: 04
#### Step: 

Description of issue
Steps need to be updated to register bot without Azure or Azure pass needed to create and register bot.

**Comment by b-deen** [comment]
Hello, these steps require an Azure subscription but do not require a monetary amount of Azure credit - everything can be completed within the free tier.  If learners do not have access to a subscription, these exercises can be omitted. Azure Passes or alternative access to Azure is currently being reviewed for this course.
