### ISSUE TITLE
LP MS-600 Build Apps with Microsoft Graph - Associate Unit 3 IAuthenticationProvider fails

### ISSUE THREAD

**Issue by JonoSuave** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#121]
# Module: Optimize data usage when using Microsoft Graph with query parameters 
## Lab/Demo: 3

Description of issue
For the labs in the MS-600, the IAuthenticationProvider interface is used almost everywhere which is supposed to be part of the Microsoft.Graph library but the compilation does not work and states that "The type or namespace name 'IAuthenticationProvider' could not be found ...

Doesn't seem this library exists under Microsoft.Graph

Repro steps:

1. Follow the steps as described in the module in VSCode: https://learn.microsoft.com/en-us/training/modules/optimize-data-usage/3-exercise-retrieve-control-information-returned-from-microsoft-graph
2. There's a step to create an AuthHelper.cs file
3. Copy the snippet provided and notice that the IAuthenticationProvider library isn't found

I'm on a Mac, using .NET 7.0
![Screenshot 2023-08-14 at 5 58 31 PM](https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/assets/22969971/d700cad3-01b9-45aa-8572-7bd1e983ac74)

**Comment by b-deen** [comment]
Hello, thanks for submitting this issue.  An update to the labs is in progress and will be published on 8/25.

**Comment by JonoSuave** [comment]
Perfect, thank you

**Comment by b-deen** [comment]
Following up here since I mentioned a specific date in my last reply.  The lab update is a week out (targeting 9/1).  Also, just to let you know, this exercise will no longer be included in the course as we are shifting to allow more time for the Teams labs.

**Comment by b-deen** [comment]
Closing issue as these exercises have been removed from the course.  Please see the course change log for more information about what has changed.
