### ISSUE TITLE
lab 02 ex 3 uses ngrok http to connect to graph which requires https

### ISSUE THREAD

**Issue by frksn** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#13]
# Module: 2
#### Step: all

Description of issue
https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/blob/master/Instructions/Labs/Lab02/Lab02-Work-with-Microsoft-Graph-lab-answer-key/04-Exercise-3-Using-change-notifications-and-track-changes-with-Microsoft-Graph.md

lab uses ngrok. free version of ngrok only allows for http
graph requires https

Repro steps:

1.
1.
1.

**Comment by b-deen** [comment]
It is possible to use the free version of ngrok for the lab.  The instructions have been updated with more information.
