### ISSUE TITLE
Mod 3 Exercise 7 Missing manifest.json file

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#17]
# Module: 03
#### Step: 01

Description of issue
Manifest file is missing in the AllFiles folder. Please copy the manifest file from https://github.com/SharePoint/sp-dev-training-spfx-teams-dev and upload is in this repo. And update the description and link to the file in this repo.

Repro steps:

1.
1.
1.

**Comment by b-deen** [comment]
Hello, this exercise does not require learners to download a manifest file.  It gets auto created in the solution and then the student copies the markup from the lab to their file.
