### ISSUE TITLE
Request: Lab Virtual Machine Installed Software List

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#2]
# Module: 00
#### Step: 00

Description of issue
Can you provide a software list like the AZ-204 repository (there are more repos doing the same)? Many students use their own laptop during course or CLPS-es do not order Labs for their students.

https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/lab.md

Repro steps:

1. Go to https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/lab.md
1.
1.

**Comment by b-deen** [comment]
Hello, this request has been noted and will be included in upcoming updates to the lab materials.  Thanks for your input on the need for the software list.
