### ISSUE TITLE
Module 4 - Lab 5 is missing

### ISSUE THREAD

**Issue by j-ankur** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#20]
Module 4 
Lab 5 - Conversational Bots
Issue: Lab is missing in GitHub

**Comment by adntobias** [comment]
is there any progress on this?

**Comment by b-deen** [comment]
Hello, There is currently no lab for this lesson.  We will have any references to a lab for this lesson updated immediately.  Apologies for any confusion here.
