### ISSUE TITLE
Lab04 - Code in LearnTeamsAppTab.tsx not present

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#22]
# Module: 00
## Lab/Demo: 04
###Exercise 01
##### Step: 00

Description of issue
None of the code referenced is present:  The app works, however the lack of the code referenced in this Task in the file specified (LearnTeamsAppTab.tsx) means the later Task 3 'Update running Visual Studio Code solution' cannot be completed, because there is no surface, Panel, PanelHeader, PanelBody, or PanelFooter sections.

Repro steps:

1. Follow the instructions, you should see the issue.  

Has something changed in the apps used to generate the app to alter the code, and/or where it is placed?  Without reliable instructions, this makes this lab exercise a mystery to try and follow.

**Comment by b-deen** [comment]
Thank you for your feedback. The lab instructions are being refreshed and we will address this feedback in upcoming updates to the instructions.
