### ISSUE TITLE
Lab01-Ex4-Task3-App instruction reversed.

### ISSUE THREAD

**Issue by VictorChin** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#24]
# Module: 01
#### Step: 00

Description of issue
In previous steps, API Permission was exposed through "ContosoApp" and not through "Identity 01". Thus it is not possible to navigate to Identity 01->Expose an API-> Add Authorized Client Application since no Scope has been previously defined on Identity 01. 
It can be done if one navigate to "ContosoApp"->API permissions->Add a client Application in Authorized client applications.

Repro steps:

1.
1.
1.

**Comment by b-deen** [comment]
Thank you for your feedback. The lab instructions are currently being refreshed and we will address this feedback in upcoming updates to the instructions.

**Comment by b-deen** [comment]
Our team was not able to reproduce this issue, so I will close this out.  Please reopen if you still have issues here.
