### ISSUE TITLE
Azure Portal link

### ISSUE THREAD

**Issue by adntobias** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#25]
# Module: 01
#### Step: all

Description of issue

Please fix the links to the Azure Portal. Except for the first link in excercise 01, the link points constantly to "azure.portal.com" instead of "portal.azure.com"
This is very irritating for the students

Repro steps:

1.
1.
1.

**Comment by b-deen** [comment]
This has been addressed in the latest lab refresh.
