### ISSUE TITLE
Teams Lab 4

### ISSUE THREAD

**Issue by adntobias** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#26]
# Module: 4
#### Step: 00

Description of issue

Please rework this exercise, the instructions are somewhat confusing everytime for the students. 
The few important parts in the linked article in "Create Bot Framework registration resource" Step 7 would be better to be written directly in the excercise, and the article should be marked as only informational.

Repro steps:

1.
1.
1.

**Comment by b-deen** [comment]
Thank you for your feedback. The lab instructions are being refreshed and we will address this feedback in upcoming updates to the instructions.

**Comment by b-deen** [comment]
Thank you for submitting this issue and feedback.  The exercises for Module 4 - Extend Teams have been updated.  The new labs will be published tomorrow on 04 Dec 2020.
