### ISSUE TITLE
SharePoint Exercise 7

### ISSUE THREAD

**Issue by adntobias** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#27]
# Module: 03
#### Step: 00

Description of issue
You refer in the exercise to a non-existent manifest file, please add a link or even better put it in the exercise.
Furthermore apperently there where changes within SharePoint or the instructions are misleading in the later SharePoint part.
Please re-check the deployment and teams integration process of the spfx solution.

Repro steps:

1.
1.
1.

**Comment by b-deen** [comment]
Thank you for your feedback. The lab instructions are being refreshed and we will address this feedback in upcoming updates to the instructions.

**Comment by b-deen** [comment]
Regarding the manifest file- it is auto-generated in the solution.  Students are not expected to download a manifest file for this exercise.  
The labs have been tested and broken instructions have been updated.
