### ISSUE TITLE
invalid character

### ISSUE THREAD

**Issue by adntobias** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#28]
# Module: 00
#### Step: 03

Description of issue

In the last command 'gulp package-solution –-ship' the first dash will provoke an error. This is some other character and hard to spot while troubleshooting, please insert a normal dash.

Repro steps:

1.
1.
1.

**Comment by b-deen** [comment]
Thank you for pointing this out.  The file has been updated.
