### ISSUE TITLE
Lab 1, exercise 2, task 4, item #7

### ISSUE THREAD

**Issue by michaeljkane** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#29]
I think this is supposed to be Hello ASPNET Core Identity 02, not Hello ASPNET Core Identity 01

**Comment by b-deen** [comment]
Hello, thank you for submitting this issue.  The issue has been addressed in the updated lab content to be published tomorrow on 04 Dec 2020.
