### ISSUE TITLE
Unauthorized login with Bots service

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#33]
# Module: 4
#### Step: 00

Description of issue
Unable to chat with the bot

 Error: Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '***' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

On the other hand, in the application registration from the Toolkit but, I see this message: Starting November 9th, 2020 end users will no longer be able to grant consent to newly registered multitenant apps without verified publishers.  Learn more
Repro steps:

1.
1.
1.

**Comment by b-deen** [comment]
Hello, thank you for submitting the issue.  We discovered a bug in the latest Teams Toolkit extension version 1.15 which is causing a bot issue.  We are working on updated lab instructions to resolve the issue, which will be published as soon as they are available.

**Comment by TheodoreShi** [comment]
You could downgrade the Microsoft Teams Toolkit extension to 1.1.2.

**Comment by b-deen** [comment]
We are hoping to have new lab instructions published today for this exercise, but in the meantime you can follow the following rollback instructions to resolve the error.

Please follow the below steps to install 1.1.2 as a workaround. 
1.	Open Visual studio code, and then click Extensions in left activity bar.
2.	To locate Microsoft Teams Toolkit under INSTALLED extensions section,  click Manage -> Install Another Version.
![temp1](https://user-images.githubusercontent.com/28913786/101660582-55044700-3a15-11eb-8c0e-acf6a4232e59.jpg)
3.	Select 1.1.2 to install the version.
![temp2](https://user-images.githubusercontent.com/28913786/101660639-63526300-3a15-11eb-8cfd-94d1fadd7310.jpg)

**Comment by b-deen** [comment]
Updated instructions have been published to address the issue.
