### ISSUE TITLE
Check graph queries to assure that they are properly written. 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#37]
Experiencing a bit of a Broad issue on **Lab 02** with regards to queries coming back invalid. 
Looking back at the queries from January it appears they have now changed with an added \ character in the strings.
This isn't working when I run the query. When I remove the \ character from the strings that do not work they run fine. 
**Note** that some strings do run with the \ character added. Similar issue with ? not being added. 

Regarding the \ character

For clarification here are some examples:
# Lab 02
#### Step 4
https://graph.microsoft.com/v1.0/groups?\$select=displayName,mail,visibility **returns invalid**
https://graph.microsoft.com/v1.0/groups?$select=displayName,mail,visibility **runs properly**

# Lab 02
#### Step 7
https://graph.microsoft.com/v1.0/groups?\$select=displayName,mail,visibility,id **returns invalid**
https://graph.microsoft.com/v1.0/groups?$select=displayName,mail,visibility,id **runs properly**

# Lab 02
#### Step 1
https://graph.microsoft.com/v1.0/groups?\$select=displayName,mail,visibility,id&\$orderBy=displayName **returns invalid**
https://graph.microsoft.com/v1.0/groups?$select=displayName,mail,visibility,id&$orderBy=displayName **runs properly**

Regarding the ? character:
 
# Lab 02
#### Step 1
https://graph.microsoft.com/v1.0/me/events **returns as invalid.** 
https://graph.microsoft.com/v1.0/me/events? **runs properly.** 

Current: https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/blob/master/Instructions/Labs/Lab02/Lab02-Work-with-Microsoft-Graph-lab-answer-key/02-Exercise-1-Using-query-parameters-when-querying-Microsoft-Graph-via-HTTP.md

Previous: https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/commit/f36b32934a54023b06a520825cbdb826c97899db#diff-d12be9ba733b7eb7be3b5cf4b7946482f0f680f0ecc1bbd8e27c73b4e80c28e5

**Comment by OGcanviz** [comment]
This is an issue from the markdown not rendering the URLs correctly in some browsers. Same issue reported in #39. Lab has been updated to correct markdown issue and will be published shortly.

**Comment by b-deen** [comment]
This issue was resulting from a formatting issue in the Markdown and has been updated.
