### ISSUE TITLE
Lab 2 - Exercise 1 - Wrong Backslashes

### ISSUE THREAD

**Issue by adntobias** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#39]
# Module: 02
#### Step: -

Description of issue
Please fix the unnecessary backslashes in the instructions.

Example: https://graph.microsoft.com/v1.0/groups?\$select=displayName,mail,visibility,id
Should be: https://graph.microsoft.com/v1.0/groups?$select=displayName,mail,visibility,id

Example: https://graph.microsoft.com/v1.0/groups?\$select=displayName,mail,visibility,id&\$orderBy=displayName
Should be: https://graph.microsoft.com/v1.0/groups?$select=displayName,mail,visibility,id&$orderBy=displayName

Repro steps:

1.
1.
1.

**Comment by b-deen** [comment]
This issue was resulting from a formatting issue in Markdown and has been updated.
