### ISSUE TITLE
Missing Numbering

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#42]
Lab 04
Exercises 8-13

Description of issue:
None of the new Exercises have numbered steps

**Comment by b-deen** [comment]
Hello, thank you for submitting this issue. We'll have the numbering fixed this week.

**Comment by IamUser1337** [comment]
Wonderful! Thanks!

**Comment by b-deen** [comment]
The exercises have been updated with numbered steps.
