### ISSUE TITLE
Missing Zip File

### ISSUE THREAD

**Issue by lexipulsar** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#43]
## Lab/Demo: 04
Exercise: 08
Task #    
"The app containing our new tab isn't installed yet, so in the Add a tab dialog, select Manage apps in the lower-right corner.

On the next screen, select the Upload a custom app link in the lower right corner of the screen below the list of existing installed apps.

Locate and select the Microsoft Teams app package, found in the ./package folder in your Visual Studio Code project to upload the app.

Microsoft Teams will display the details of the app in a dialog. Select the Add button to install the app into the current team:"

Description of issue
The previous commands did not generate a zip file to be uploaded into teams. I will include a screenshot below with the learn-msteams-teamwork directory below.

![image](https://user-images.githubusercontent.com/78499909/123153193-67832280-d433-11eb-8c08-ae2fd0632e23.png)

![image](https://user-images.githubusercontent.com/78499909/123153127-576b4300-d433-11eb-9040-84772f19a85c.png)

**Comment by b-deen** [comment]
Hello, this exercise was retested today and the package was generated as expected.  There does not appear to be an issue with the instructions.  Please follow up if you experience the same issue after going through the steps again.
