### ISSUE TITLE
Error Lab 04 MS600 and modules ahead

### ISSUE THREAD

**Issue by JoaoAlmeidaPoa** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#44]
# Module: 04

Description of issue

Hi, a few days ago, when I start to teach MS-600, when arrive at module 04, I get some problems with authentication with teams toolkit extension for vscode.

**1. Version Teams Toolkit outdated and Exercises too:** The extension inside module tells to use a version 1.1.2 but, when I try to run the module 04 exercise 05 and after, when a try to open the icon "Open Microsoft Teams Toolkit" the extension hangs up with a message "Waiting for user authentication..." after I connect to my office 365 account, and nothing happens and the scream appears to be freeze.
I try to run another versions of tollkit from 1.1.2 until 1.2.3 and I get the same result.
When I try to run with version 2.0.1 the things works but the exercise changes significantly when I will need one of two ways, get new exercises or create all exercises after module 04 exercise 05 and after or if has an update from module that is compatible to version 2.2.0 of teams toolkit (i think that is best option), can anyone share it or update the master branch of course at git hub.

**2. Manifest File outdated:** Another problem, is when you create a manifest file to run with appstudio, the version created by v.1.1.2 is manifest 1.5, but the current version of manifest file from updated teams version is 1.9.

**3. Teams Desktop App is Outdated:** At lab machine on Labs On Demand, when you try to start the teams desktop app, the app require to be updated to open and run.

Anyone has this problem?

Repro steps:

1. Run the module 04 and after modules with course requirements
![Screenshot_1 - labms600](https://user-images.githubusercontent.com/5376130/126323736-06a31656-1aa0-4d08-ba84-46021be72f73.png)
![Screenshot_2 - labms600](https://user-images.githubusercontent.com/5376130/126323741-45e0ed6f-ea5e-4c58-83b1-c029aefc1ac3.png)

**Comment by b-deen** [comment]
Hello, thank you for submitting this issue.  We are looking into these and will follow up with any additional guidance here and/or updated exercises as appropriate.  Thank you.

**Comment by JoaoAlmeidaPoa** [comment]
Hi, did you see the exercises or have any updates about it?

**Comment by b-deen** [comment]
Hello, my apologies - it looks like my last comment didn’t post on Monday for some reason.  The exercises will be reviewed in more detail next week, but in the meantime you may use the exercises from the following Learn modules in place of exercises 9-13 (SSO and Teamwork endpoint topics). 

https://docs.microsoft.com/en-us/learn/modules/msteams-sso/

https://docs.microsoft.com/en-us/learn/modules/msteams-teamwork-endpoint/

**Comment by b-deen** [comment]
Hello, the exercises for the Teams module were updated on Friday.  These issues are now resolved.
