### ISSUE TITLE
Teams Toolkit Version 1.1.2

### ISSUE THREAD

**Issue by StevenLODS** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#45]
# Module: 04
#### Step: 6

Description of issue:

We're running into an issue during Exercise 6, Task 1, Step 6. 

When attempting to proceed within the instructional content we're running into an issue with the Team Toolkit 1.1.2. There is an authentication error saying "Waiting on user authentication" but never prompts or never proceeds.

![image](https://user-images.githubusercontent.com/78036494/128418235-781608c7-f7f8-4499-9b84-3ced237e4110.png)

I believe if you update to the latest version it works, but the UI is completely different and doesn't match the instructional content provided.

**Comment by b-deen** [comment]
Hello, thank you for submitting this issue.  Updated labs that use the Yeoman generator should be published early next week.  The labs will likely eventually be updated to use v2 of the Toolkit.

**Comment by b-deen** [comment]
The exercises for this module have been updated and are no longer using the Toolkit at this time.
