### ISSUE TITLE
Error - Lab04-Extending-Teams

### ISSUE THREAD

**Issue by dennyeapen** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#46]
Lab04-Extending-Teams
Exercise 1: Creating an app manifest in Microsoft Teams
Task 2: Configure an app manifest using App Studio
Update app manifest
4. Now update the tab name by following the steps below:
i. In the App Studio navigation pane, select Capabilities > Tabs.
ii. Locate **the only personal tab** in the project, and select ... > Edit on that tab.

There is no personal tab in the project.

**Comment by b-deen** [comment]
Hi, thank you for submitting this issue.  The exercises for Module 4 were updated on Friday, so this issue is no longer relevant.
