### ISSUE TITLE
Lab 11 Exercise 10 No Lab Exercise title/Header and screenshots broken.

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#47]
### Exercises-10 & 11
Creating-conversational-bots

**Issues:** 

No Lab Exercise title/Header.
Screenshots are broken. 

**Steps to Reproduce:**

https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/blob/master/Instructions/Labs/Lab04/2Lab04-Extending-Teams-lab-answer-key/11-Exercise-10-Creating-conversational-bots.md
![2021-08-16_125455](https://user-images.githubusercontent.com/62302805/129600787-6c693b0b-ee3b-468e-9ffa-ad193b944a33.JPG)
![2021-08-16_125504](https://user-images.githubusercontent.com/62302805/129600802-0dc3b144-a4bb-4492-8835-4e8e3414649d.JPG)

**Comment by b-deen** [comment]
Thank you, these have been updated.
