### ISSUE TITLE
Exercises 13 and 14 are labeled "Exercises 8 and 9

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#48]
Description of issue
Exercises 13 and 14 are labeled "Exercises 8 and 9"
Repro steps:

Exercise 13:

https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/blob/master/Instructions/Labs/Lab04/2Lab04-Extending-Teams-lab-answer-key/14-Exercise-13-Getting-started-with-the-teamwork-endpoint.md

Exercise 14:
https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/blob/master/Instructions/Labs/Lab04/2Lab04-Extending-Teams-lab-answer-key/15-Exercise-14-Configure-a-built-in-tab-with-Microsoft-Graph.md

**Comment by b-deen** [comment]
Thank you, these have been updated.
