### ISSUE TITLE
No individual numbering in lab steps. 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#52]
All Labs

The numbering is missing. 
No way to task track for students. 

Would it be possible to add some numbering?
Thanks

**Comment by TesterTesterson1004** [comment]
Concur - numbering is important to a Student when tracking changes that have or have not made within a course sequence, even more so when (in a long lab) they may need to save a lab and return to it later.  Without numbering, this is difficult.

Can Course Owner please consider adding numbering to the course Steps?

**Comment by dahans-msft2** [comment]
Good feedback, we'll work on adding step numbers as we update content. Thank you.
