### ISSUE TITLE
 Screenshot above "Summary" at the bottom is broken.

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#53]
# Module: 04
#### Step: Last screenshot

Description of issue

Repro steps:

https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/blob/master/Instructions/Labs/4-Develop%20apps%20for%20Microsoft%20Teams/04-Create%20interactive%20conversational%20bots

Screenshot above "Summary" at the bottom is broken.

![2021-10-18_143331](https://user-images.githubusercontent.com/62302805/137787212-05479004-1603-4cc9-9be2-51c7921bd584.JPG)
/03-Exercise-Sending%20proactive%20messages%20from%20bots.md#test-the-bot-sending-new-messages

**Comment by dahans-msft2** [comment]
Found the issue - image file was named incorrectly, will be resolved in next PR.

**Comment by dahans-msft2** [comment]
Resolved in PR #57, which will be merged to master after 5pm PDT.
