### ISSUE TITLE
configure the web app's middleware to add support for the Microsoft Graph throws error when building application

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#54]
https://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/blob/master/Instructions/Labs/1-Implement%20Microsoft%20identity/02-Application%20types%20in%20Microsoft%20identity/02-Exercise-Web%20apps%20that%20sign%20in%20users%20and%20call%20APIs.md#configure-the-web-application-with-the-azure-ad-application

services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
    .EnableTokenAcquisitionToCallDownstreamApi(new string[] { "User.Read" })
    .AddMicrosoftGraph("https://graph.microsoft.com/v1.0", "User.Read")
    .AddInMemoryTokenCaches()

![2021-11-02_155221](https://user-images.githubusercontent.com/62302805/139947959-68db6d71-d6e8-4532-bed9-8efb603673db.JPG)
;

**Comment by MOC-Labs-Review** [comment]
Some solution files in the Allfiles folder would help to QA the VS code files. Or a screenshot periodically to show the formatting.

**Comment by hope77777** [comment]
Some solution files in the Allfiles folder would help to QA the VS code files. Or a screenshot periodically to show the formatting.

**Comment by dahans-msft2** [comment]
Will look into this in our next update.  I don't understand what error you're receiving though. What are the screenshots showing here? Thank you!

**Comment by b-deen** [comment]
Closing issue as this lab exercise is no longer in the course.
