### ISSUE TITLE
Screenshot is slightly different. UI change for Module 3 Exercise 1 Sharepoint

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#55]
https://github.com/MOC-Labs-Review/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services/blob/master/Instructions/Labs/3-Extend%20Microsoft%20365/01-Introduction%20to%20customizing%20and%20extending%20SharePoint/01-Exercise-Create%20and%20configure%20your%20SharePoint%20Online%20developer%20tenant.md#exercise-1-create-and-configure-your-sharepoint-online-developer-tenant

Current Instructions:

![2021-11-03_131929](https://user-images.githubusercontent.com/62302805/140151265-36df771e-4ab9-4fff-b786-06ef748681d3.JPG)

New UI experience:

![2021-11-03_131915](https://user-images.githubusercontent.com/62302805/140150834-70d4081b-eb1a-4b7d-bed3-0287b7931198.JPG)

**Comment by dahans-msft2** [comment]
Updated image, will be resolved in next PR.

**Comment by dahans-msft2** [comment]
Resolved in PR #57, which will be merged to master after 5pm PDT.
