### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by berkenbrack** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#56]
Feature Requests

Hello, we have had the following items be requested as additional features for this title:

- Provide finished versions of the file or project as an option for students to review their coding syntax, helping save time  troubleshooting coding errors and having an example to work from. 

- Tenant accounts be populated with sample data sets outside of a basic list of users. Items such as populating the accounts with emails in the admin inbox, calendar appointments, and O365 groups, with members and owner in the tenants.  This would give more valuable information for the programs to extract and return.

**Comment by b-deen** [comment]
Thank you for the feedback. We are actively working on updating the lab experience.
