### ISSUE TITLE
Missing Step numbers throughout the MS-600T00 lab

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#90]
# Module: All 4 Modules
#### Step: Entire file

Description of issue
Step numbers are missing in the entire file, unable to track the lab progress. 

Repro steps:
Modules>> Lab >> Steps#???

**Comment by dahans-msft2** [comment]
Will work on adding lab steps as we update content and make improvements.  Thank you.
