### ISSUE TITLE
Notes about node.js version 

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#95]
# Module: 3
#### Step: 1

Description of issue:
Notes are very confusing 'If Node.js version is showing incorrectly during Exercise 1, Task 1, Step 1, please wait 3 minutes before proceeding with this Exercise.' So, the task is to perform https://{{REPLACE_WITH_YOUR_TENANTID}}-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx. 

Not sure what exactly the note in the beginning of the modules is referring too.

Intermittently the sharepoint site was throwing an error.

**Comment by b-deen** [comment]
Closing issue as Module 3 no longer contains labs.
