### ISSUE TITLE
Creating the folder 

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#97]
# Module: 1
### Task: Create the folder

Description of issue
Detailed instruction must be included in the lab for the users to 'create the folder' on a specified path for each lab or exercise. 

On each exercise under the lab the user has to create the folder and create the Azure AD application (App registration).  At times the same App names have been reused in other exercises too instead of using a different App name.

**Comment by b-deen** [comment]
Thank you for this feedback.  We have removed redundant exercises in the Identity section.  We are working to streamline the lab experience across all sections of the course.
