### ISSUE TITLE
Output Screenshots or Expected results are missing

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#98]
# Module: Entire 
### Task: All

Description of issue
While testing the application only 'hello world' is listed as the output and the expected output is missing.

Saving the files in the Visual code editor instructions are missing in the entire lab exercise, as per the default build the output 'Hello World' would be displayed even if there is an error in the code. 

Saving the files would help us to know the exact issue before executing the dotnet run.

More detailed instructions or a screenshot can address these issues as what to expect as the output.

For module 1 exercises most of the instruction says 'Depending on the browser, you are using, a popup window will load or the page will redirect to the Azure AD sign in prompt.' however it doesn't redirect to the Azure AD sign in.

Also detailed instructions needs to be provided - after calling the local host (once the output is displayed), best practice is to close the InPrivate mode browser.

**Comment by b-deen** [comment]
Thank you for your feedback re: solution files.   The corresponding modules on Learn do link to solution files, which we will be adding here shortly.  

Re: the module 1 issue - this issue arises when you select "Yes" to remain signed on on the "Stay signed in?" prompt, which causes caching of credentials and prevents token acquisition as expected in the lab.  Learners should be sure to select "No" on the "Stay signed in?" prompt to avoid this issue.  We have added a note to the labs and will explore additional ways to prevent this scenario.
