### ISSUE TITLE
Issue in Bot Creation 

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#99]
# Module: 4
### Task: 1

Description of issue

Unable to proceed after this step due to the insufficient privilege access Bot > Settings > Channel > Manage > Certificate & Secrets'. Also identified Channels (deprecated).

![Channels_deprecated](https://user-images.githubusercontent.com/92770552/150239224-98499d0e-6aaf-4bd9-a36d-48dc98b5f235.png)

Azure pass subscription has been attached to the tenant. 

Recently labs with Azure subscriptions are instructed to create the new outlook account to redeem the Azure pass credit instead of claiming against the tenant. In such scenarios detailed instructions need to be provided to apply the Azure pass credit from one tenant to another. A supporting document for 'Assigning the Azure pass to another tenant' can be uploaded along with 'How to claim the Azure pass? (Which is currently shared by the lab instructors before the lab process)'   

Repro steps:

1. Bot > Settings > Channel > Manage > Certificate & Secrets

**Comment by b-deen** [comment]
Thank you for submitting these issues.  Closing as both of these are no longer active issues (Teams labs have been updated since this comment, and course no longer requires an Azure Pass with credit.)
